# This test is to see if the `is burning` condition works properly.
# Before, something like `if {x} is burning` would try to compare {x} to the burning damage cause
# instead of whether or not the entity was burning.
test "burning":
	assert "burning" parsed as damage cause is burning with "burning damage cause compare"
	spawn a pig at event-location:
		set burning time of event-entity to 9000 ticks
		assert entity within event-entity is burning with "is burning failed"
		assert event-entity is burning with "is burning failed ##2"
		clear entity within event-entity
