test "EffSpread - 1":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1}, {_2 through 9::*} and {_10}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2 through 9::*} is 2, 3, 4, 5, 6, 7, 8 and 9 with "Spread to {_2 through 9::*} failed"
	assert {_10} is 10 with "Spread to {_10} failed"

test "EffSpread - 2":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1}, {_2}, {_3}, {_4 through 8::*}, {_9}, {_10}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2} is 2 with "Spread to {_2} failed"
	assert {_3} is 3 with "Spread to {_3} failed"
	assert {_4 through 8::*} is 4, 5, 6, 7 and 8 with "Spread to {_4 through 8::*} failed"
	assert {_9} is 9 with "Spread to {_9} failed"
	assert {_10} is 10 with "Spread to {_10} failed"

test "EffSpread - 3":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1} and {_2 through 10::*}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2 through 10::*} is 2, 3, 4, 5, 6, 7, 8, 9 and 10 with "Spread to {_2 through 10::*} failed"

test "EffSpread - 4":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1 through 9::*} and {_10}
	assert {_1 through 9::*} is 1, 2, 3, 4, 5, 6, 7, 8 and 9 with "Spread to {_1 through 9::*} failed"
	assert {_10} is 10 with "Spread to {_10} failed"

test "EffSpread - 5":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1 through 8::*}, {_9} and {_10}
	assert {_1 through 8::*} is 1, 2, 3, 4, 5, 6, 7 and 8 with "Spread to {_1 through 8::*} failed"
	assert {_9} is 9 with "Spread to {_9} failed"
	assert {_10} is 10 with "Spread to {_10} failed"

test "EffSpread - 6":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1} and {_2 through 10::*}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2 through 10::*} is 2, 3, 4, 5, 6, 7, 8, 9 and 10 with "Spread to {_2 through 10::*} failed"

test "EffSpread - 6":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1}, {_2} and {_3 through 10::*}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2} is 2 with "Spread to {_2} failed"
	assert {_3 through 10::*} is 3, 4, 5, 6, 7, 8, 9 and 10 with "Spread to {_3 through 10::*} failed"

test "EffSpread - 7":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1}, {_2} and {_3}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2} is 2 with "Spread to {_2} failed"
	assert {_3} is 3 with "Spread to {_3} failed"

test "EffSpread - 8":
	parse:
		spread {_1 through 10::*} across {_1}
	assert parse logs contain "The spread target must be a list of settable expressions" with "EffSpread did not error with a single spread target"

test "EffSpread - 9":
	set {_1 through 10::*} to 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10
	spread {_1 through 10::*} across {_1} and {_2}
	assert {_1} is 1 with "Spread to {_1} failed"
	assert {_2} is 2 with "Spread to {_2} failed"

test "EffSpread - 10":
	parse:
		spread {_1 through 10::*} across {_1} or {_2}
	assert first element of parse logs starts with "Can't understand" with "EffSpread did not error with an or spread target"

test "EffSpread - 11":
	parse:
		spread {_list::*} across all players and all players
	broadcast "PRASE LOGS" and parse logs
	assert first element of parse logs is "All expressions in the spread target list must be settable" with "EffSpread did not error when spread target couldn't be set"
